CC = gcc
CFLAGS = -c -Wall -Werror -Wextra

B = ../build/graph

all: go

go: graph.c bobir.c  $(B)

$(B): graph.o bobir.o
	$(CC) $^ -o $@


clean:
	rm -rf *.o
	rm 	../build/*

rebuild: clean all

format: 
	clang-format -i *.c *.h
	cppcheck --enable=all --suppress=missingIncludeSystem ./